apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.beta.kubernetes.io/gid: '0'
  labels:
    type: local
  name: staging-slave01-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/mysql-slave01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: local
  name: staging-slave01-pvc  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: staging-slave01-pv
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10G


